FROM python:3.11-bullseye
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get upgrade -y

WORKDIR /back
COPY ./requirements.txt ./
RUN pip install -r ./requirements.txt
# RUN pip uninstall -y gunicorn
# RUN pip install -y uwsgi

COPY ./sender ./sender

COPY ./config.py ./

COPY ./entrypoint.sender.sh ./
RUN chmod +x entrypoint.sender.sh
ENTRYPOINT ["bash", "entrypoint.sender.sh"]
