FROM python:3.11-bullseye
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get upgrade -y

WORKDIR /back
COPY ./requirements.txt ./
RUN pip install -r ./requirements.txt
# RUN pip uninstall -y gunicorn
# RUN pip install -y uwsgi

COPY ./back ./back

COPY ./config.py ./

COPY ./entrypoint.back.sh ./
RUN chmod +x entrypoint.back.sh

RUN useradd -ms /bin/bash celery
RUN chown -R celery:celery /back
USER celery

ENTRYPOINT ["bash", "entrypoint.back.sh"]
