# docker pull selenium/standalone-chrome:latest
# To see what is happening inside the container, head to
# http://localhost:7900/?autoconnect=1&resize=scale&password=secret
version: "3.8"
services:
  selenium:
    env_file: .env
    image: selenium/standalone-chrome:latest
    shm_size: "2gb"
    restart: always

    ports:
      - "127.0.0.1:4444:4444"
      # secret
      - "127.0.0.1:7900:7900"
    logging:
      options:
        max-size: "10m"
        max-file: "1"

  db:
    env_file: .env
    image: postgres:14.1-alpine
    command:
      [
        "postgres",
        "-c",
        "log_statement=${db_log_statement}",
        "-c",
        "log_destination=stderr",
      ]
    restart: always
    environment:
      POSTGRES_USER: ${db_user}
      POSTGRES_PASSWORD: ${db_pass}
      POSTGRES_DB: ${db_user}
    volumes:
      - news-db-data:/var/lib/postgresql/data
    # expose:
    #   - "5432"
    ports:
      - "${db_port}:5432"
    healthcheck:
      test: pg_isready -U ${db_user}
      interval: 2s
      timeout: 3s
      retries: 40
    logging:
      options:
        max-size: "10m"
        max-file: "1"

  # redis:
  #   env_file: .env
  #   image: redis:6
  #   restart: always
  #   ports:
  #     - "127.0.0.1:6379:6379"
  #   mem_limit: 500M
  #   mem_reservation: 100m
  #   cpus: 0.3
  #   healthcheck:
  #     test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
  #     interval: 2s
  #     timeout: 3s
  #     retries: 40
  #   logging:
  #     options:
  #       max-size: "10m"
  #       max-file: "1"
volumes:
  news-db-data:
    name: news-db-data
    external: true
