# Generated by Django 4.2.6 on 2023-10-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clients",
            fields=[
                (
                    "clients_id",
                    models.BigAutoField(
                        db_column="clients_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, default="", max_length=200, unique=True
                    ),
                ),
                ("news_type", models.CharField(blank=True, default="", max_length=200)),
                ("monday", models.CharField(blank=True, default="10:00", max_length=5)),
                (
                    "tuesday",
                    models.CharField(blank=True, default="10:00", max_length=5),
                ),
                (
                    "wednesday",
                    models.CharField(blank=True, default="10:00", max_length=5),
                ),
                (
                    "thursday",
                    models.CharField(blank=True, default="10:00", max_length=5),
                ),
                ("friday", models.CharField(blank=True, default="10:00", max_length=5)),
                (
                    "saturday",
                    models.CharField(blank=True, default="10:00", max_length=5),
                ),
                ("sunday", models.CharField(blank=True, default="10:00", max_length=5)),
                ("phone", models.CharField(blank=True, default="", max_length=100)),
                ("utc_created", models.BigIntegerField(blank=True, default=0)),
                ("utc_updated", models.BigIntegerField(blank=True, default=0)),
                ("utc_payed", models.BigIntegerField(blank=True, default=0)),
            ],
            options={
                "verbose_name_plural": "Clients",
            },
        ),
    ]
