# Generated by Django 4.2.6 on 2023-10-31 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_remove_clients_friday_remove_clients_monday_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="days_in_week",
            field=models.IntegerField(blank=True, db_index=True, default=1),
        ),
    ]
