# Generated by Django 4.2.6 on 2023-11-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_alter_clients_days_in_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=100, unique=True),
        ),
    ]
